version: 2
sources:
- name: gregor_test_study
  schema: main
  tables:
  - name: GREGoR_synthetic_participant_revised07Aug2024
    description: Source table for GREGoR_synthetic_participant_revised07Aug2024.
    columns:
    - name: AnVIL_GREGoR_GSS_U07_GRU_participant_id
      description: '{{ doc("GREGoR_synthetic_participant_revised07Aug2024_anvil_gregor_gss_u07_gru_participant_id")
        }}'
    - name: affected_status
      description: '{{ doc("GREGoR_synthetic_participant_revised07Aug2024_affected_status")
        }}'
    - name: age_at_enrollment
      description: '{{ doc("GREGoR_synthetic_participant_revised07Aug2024_age_at_enrollment")
        }}'
    - name: age_at_last_observation
      description: '{{ doc("GREGoR_synthetic_participant_revised07Aug2024_age_at_last_observation")
        }}'
    - name: ancestry_detail
      description: '{{ doc("GREGoR_synthetic_participant_revised07Aug2024_ancestry_detail")
        }}'
    - name: consent_code
      description: '{{ doc("GREGoR_synthetic_participant_revised07Aug2024_consent_code")
        }}'
    - name: family_id
      description: '{{ doc("GREGoR_synthetic_participant_revised07Aug2024_family_id")
        }}'
    - name: gregor_center
      description: '{{ doc("GREGoR_synthetic_participant_revised07Aug2024_gregor_center")
        }}'
    - name: internal_project_id
      description: '{{ doc("GREGoR_synthetic_participant_revised07Aug2024_internal_project_id")
        }}'
    - name: maternal_id
      description: '{{ doc("GREGoR_synthetic_participant_revised07Aug2024_maternal_id")
        }}'
    - name: missing_variant_case
      description: '{{ doc("GREGoR_synthetic_participant_revised07Aug2024_missing_variant_case")
        }}'
    - name: paternal_id
      description: '{{ doc("GREGoR_synthetic_participant_revised07Aug2024_paternal_id")
        }}'
    - name: phenotype_description
      description: '{{ doc("GREGoR_synthetic_participant_revised07Aug2024_phenotype_description")
        }}'
    - name: pmid_id
      description: '{{ doc("GREGoR_synthetic_participant_revised07Aug2024_pmid_id")
        }}'
    - name: prior_testing
      description: '{{ doc("GREGoR_synthetic_participant_revised07Aug2024_prior_testing")
        }}'
    - name: Self_relationship
      description: '{{ doc("GREGoR_synthetic_participant_revised07Aug2024_self_relationship")
        }}'
    - name: Self_relationship_detail
      description: '{{ doc("GREGoR_synthetic_participant_revised07Aug2024_self_relationship_detail")
        }}'
    - name: reported_ethnicity
      description: '{{ doc("GREGoR_synthetic_participant_revised07Aug2024_reported_ethnicity")
        }}'
    - name: reported_race
      description: '{{ doc("GREGoR_synthetic_participant_revised07Aug2024_reported_race")
        }}'
    - name: sex
      description: '{{ doc("GREGoR_synthetic_participant_revised07Aug2024_sex") }}'
    - name: sex_detail
      description: '{{ doc("GREGoR_synthetic_participant_revised07Aug2024_sex_detail")
        }}'
    - name: solve_status
      description: '{{ doc("GREGoR_synthetic_participant_revised07Aug2024_solve_status")
        }}'
    - name: twin_id
      description: '{{ doc("GREGoR_synthetic_participant_revised07Aug2024_twin_id")
        }}'
  - name: GREGoR_synthetic_phenotype
    description: Source table for GREGoR_synthetic_phenotype.
    columns:
    - name: AnVIL_GREGoR_GSS_U07_GRU_phenotype_id
      description: '{{ doc("GREGoR_synthetic_phenotype_anvil_gregor_gss_u07_gru_phenotype_id")
        }}'
    - name: additional_details
      description: '{{ doc("GREGoR_synthetic_phenotype_additional_details") }}'
    - name: additional_modifiers
      description: '{{ doc("GREGoR_synthetic_phenotype_additional_modifiers") }}'
    - name: onset_age_range
      description: '{{ doc("GREGoR_synthetic_phenotype_onset_age_range") }}'
    - name: ontology
      description: '{{ doc("GREGoR_synthetic_phenotype_ontology") }}'
    - name: participant_id
      description: '{{ doc("GREGoR_synthetic_phenotype_participant_id") }}'
    - name: presence
      description: '{{ doc("GREGoR_synthetic_phenotype_presence") }}'
    - name: term_id
      description: '{{ doc("GREGoR_synthetic_phenotype_term_id") }}'
