name: gregor_test_study
version: 1.0.0
profile: 'anvil_duckdb'
model-paths:
- models
macro-paths:
- macros
snapshot-paths:
- snapshots
clean-targets:
- target
- dbt_packages
models:
  +schema: main
  +materialized: table
  participant:
    gregor_test_study_stg_participant:
      +schema: main
      +materialized: table
  phenotype:
    gregor_test_study_stg_phenotype:
      +schema: main
      +materialized: table
