name: m00m00
version: 1.0.0
profile: include
model-paths:
- models
macro-paths:
- macros
snapshot-paths:
- snapshots
clean-targets:
- target
- dbt_packages
models:
  +schema: m00m00_data
  +materialized: table
  participant:
    m00m00_stg_participant:
      +schema: m00m00_data
      +materialized: table
  condition:
    m00m00_stg_condition:
      +schema: m00m00_data
      +materialized: table
