name: m00m00
version: 1.0.0
profile: pgtest
model-paths:
- models
macro-paths:
- macros
snapshot-paths:
- snapshots
clean-targets:
- target
- dbt_packages
models:
    m00m00:
        +schema: m00m00_data
        +materialized: table
        participant:
            m00m00_raw_participant: null
            m00m00_stg_participant: null
        condition:
            m00m00_raw_condition: null
            m00m00_stg_condition: null
