name: 'tgt'
version: '1.0.0'
profile: 'pgtest'

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets: 
  - "target"
  - "dbt_packages"


models:
  tgt:
    +materialized: table
    +schema: moo_ftd_data

    tgt_participant:

    tgt_measurement:

    tgt_condition:

    tgt_event:




      

  
