name: 'ftd'
version: '1.0.0'


profile: 'pgtest'

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets: 
  - "target"
  - "dbt_packages"

models:
  ftd:
    +materialized: table
    m00m00:
      +schema: moo_ftd_data
      moo_ftd_participant:
      moo_ftd_condition:
      moo_ftd_measurement:
      moo_ftd_event:
    arfarf:
      +schema: arf_ftd_data
      arf_ftd_participant:
      arf_ftd_condition:
      arf_ftd_measurement:
      arf_ftd_event:
