name: 'ftd'
version: '1.0.0'


profile: 'pgtest'

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets: 
  - "target"
  - "dbt_packages"

models:
  ftd:
    +schema: ftd_data
    +materialized: table
    participant:
    condition:
    measurement:
    event:



      

  
