name: 'arfarf'
version: '1.0.0'
profile: 'pgtest'


model-paths: ["models"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  arfarf:
    +schema: arf_data
    +materialized: table

    participant:
      arf_raw_participant:
      arf_stg_participant:
        
    condition:
      arf_raw_condition:
      arf_stg_condition:

      

  
