name: mewmew
version: 1.0.0
profile: pgtest
model-paths:
- models
macro-paths:
- macros
snapshot-paths:
- snapshots
clean-targets:
- target
- dbt_packages
models:
  +schema: mewmew_data
  +materialized: table
  participant:
    mewmew_raw_participant:
      +schema: mewmew_data
      +materialized: table
    mewmew_stg_participant:
      +schema: mewmew_data
      +materialized: table
  condition:
    mewmew_raw_condition:
      +schema: mewmew_data
      +materialized: table
    mewmew_stg_condition:
      +schema: mewmew_data
      +materialized: table
