name: 'fhir_modules'
version: '1.0.0'

profile: 'pgtest'

clean-targets:  
  - "target"
  - "dbt_packages"

model-paths: ["models"]
macro-paths: ["macros"]

models:
  fhir_modules:
    participant:
      +materialized: view
      +schema: moo_data
    condition:
      +materialized: view
      +schema: moo_data
